# Generated by Django 3.0.5 on 2020-04-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contienente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dpto', models.CharField(max_length=100)),
                ('cod_dpto', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('dir_empresa', models.CharField(max_length=100)),
                ('tel_empresa', models.CharField(max_length=100)),
                ('correo_empresa', models.EmailField(max_length=254)),
                ('cant_sucursales', models.IntegerField()),
                ('latitud_empresa', models.CharField(max_length=100)),
                ('longitud_empresa', models.CharField(max_length=100)),
                ('foto_empresa', models.FileField(null=True, upload_to='fotosEmpresa/%Y/%m/%d')),
                ('admin_empresa', models.CharField(max_length=100)),
                ('descripcion_empresa', models.CharField(max_length=800)),
                ('archivo_mapaCiudad', models.FileField(null=True, upload_to='mapasEmpresa/%Y/%m/%d')),
                ('sitio_web_empresa', models.URLField()),
                ('ciudad_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Ciudades')),
                ('dpto_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('apellido_encargado', models.CharField(max_length=100)),
                ('cc_encargado', models.CharField(max_length=50)),
                ('dir_encargado', models.CharField(max_length=120)),
                ('cel_encargado', models.CharField(max_length=10)),
                ('tel_emergencia', models.CharField(max_length=10)),
                ('foto_encarcado', models.FileField(null=True, upload_to='fotoEncargados/%Y/%m/%d')),
                ('eps_encargado', models.CharField(max_length=100)),
                ('arl_encargado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_idioma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mapa', models.CharField(max_length=100)),
                ('archivo_mapa', models.FileField(null=True, upload_to='mapas/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pais', models.CharField(max_length=100)),
                ('cod_pais', models.CharField(max_length=5)),
                ('continente_pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Continentes')),
                ('idioma_pais', models.ManyToManyField(to='sucursales.Idiomas')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_perfil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_red_social', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_sucursal', models.CharField(max_length=100)),
                ('nom_sucursal', models.CharField(max_length=100)),
                ('dir_sucursal', models.CharField(max_length=100)),
                ('tel_sucursal', models.CharField(max_length=100)),
                ('descripcion_sucursal', models.CharField(max_length=800)),
                ('foto_sucursal', models.FileField(null=True, upload_to='fotosSucursales/%Y/%m/%d')),
                ('sitio_web_sucursal', models.URLField()),
                ('ciudad_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Ciudades')),
                ('dpto_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Departamentos')),
                ('empresa_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Empresas')),
                ('encargado_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Encargado')),
                ('estado_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Estado')),
                ('pais_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Paises')),
                ('ruta_mapaSucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Mapas')),
            ],
        ),
        migrations.AddField(
            model_name='encargado',
            name='estado_encargadp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Estado'),
        ),
        migrations.AddField(
            model_name='encargado',
            name='perfil_encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Perfil'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='estado_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Estado'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='pais_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Paises'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='red_sociales',
            field=models.ManyToManyField(to='sucursales.RedesSociales'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='pais_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Paises'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='dpto_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.Departamentos'),
        ),
    ]
