# Generated by Django 3.0.5 on 2020-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continentes',
            old_name='nom_contienente',
            new_name='nom_continente',
        ),
    ]
