# Generated by Django 3.0.5 on 2020-04-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_auto_20200427_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continentes',
            old_name='nom_continente',
            new_name='nombre',
        ),
    ]
